end/demo1/bookdemo/bookdemo/urls.py
from django.contrib import admin
from django.urls import path, include
#路由网址 每一个网址都需要绑定视图函数 视图函数给予页面返回
#每一个路由都需要和视图函数绑定
#MVT V 视图函数 3个作用 接受请求 处理数据 返回响应

urlpatterns = [


    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls', namespace='polls')),
    path('download', include('download.urls', namespace='download')),

    # 路由修改
    path('', include('booktest.urls', namespace='booktest'))

    #1.使用path将booktest的路由 进行包含
    # path('booktest/', include('booktest.urls'))


]
#项目的所有路由地址配置文件
#admin路由是django自带的后台管理路由
#总的路由列表==项目路由文件 使用include包含应用路由文件

#硬编码 在html文件中有很多超级链接 其中herf属性如果写成绝对路径 这种就叫硬编码
#在开发的过程中可能需要反复修改路由，若使用硬编码非常不方便
#需要解除硬编码
#1.需要给应用一个app_name='应用名' 写在应用的urls.py文件中
#2.在项目路由中给应用分流时 在include中提供命名空间
#3.在应用中给每一个路由一个名字
#4.在html中使用时，href={% url '应用名:路由名字'  实参列表 %}
#以前定位路由 靠总路由正则表达式+应用路由正则表达式
#接触硬编码后 使用 应用名字+应用路由名字

end/demo1/bookdemo/booktest/urls.py
#每一个路由文件中必须编写路由数组

#引入路由绑定函数
from django.conf.urls import url
#2.引入路由函数绑定的的视图
from . import views
app_name = 'booktest'
urlpatterns = [
    url(r'^$',                views.index,      name='index'),
    url(r'^detail/(\d+)/$',     views.detail,     name='detail'),
    url(r'^about/$',          views.about,      name='about'),
    url(r'^deletebook/(\d+)/$', views.deletebook, name='deletebook'),
    url(r'^deletehero/(\d+)/$', views.deletehero, name='deletehero'),
    url(r'^addhero/(\d+)/$', views.addhero, name='addhero'),
    url(r'^edithero/(\d+)/$',views.edithero, name='edithero')

]

end/demo1/bookdemo/polls/urls.py
from django.conf.urls import url
from . import views
app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^detail/(\d+)/$', views.detail, name="detail"),
    url(r'^result/(\d+)/$', views.result, name='result'),
    url(r'^login/$', views.login, name='login'),
    url(r'^regist/$', views.regist, name='regist'),
    url(r'^logout/$', views.logout, name='logout'),
]

end/demo1/bookdemo/templates/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加英雄</title>
</head>
<body>
    <div class="container">
        #向当前页面的路由发起post请求
        <form action="#" method="post">
            英雄名字：<input type="text"  name="heroname" placeholder="请输入英雄名字" value="{{hero.name}}">
            <br>
            英雄技能：<input type="text" name="herocontent" placeholder="请输入技能" value="{{hero.content}}">
            <br>
            英雄性别：<input type="radio" value="female"  name="sex" checked>女 <input type="radio" value="female" name="sex" checked>男
            <br>
            <input type="submit" value="提交">
        </form>
    </div>


</body>
</html>

end/demo1/bookdemo/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <h1>这是详情页</h1>
    <div>
        <h2>书名：{{book.title}}</h2>
        <ul>
           {% for hero in book.hero_set.all  %}
            <li>
                {{hero.name}}--{{hero.gender}}--{{hero.content}}
                <a href="{% url 'booktest:edithero'   hero.id %}">编辑</a>
                <a href="{% url 'booktest:deletehero' hero.id %}">删除</a>
            </li>
            {% endfor %}
        </ul>
        <a href="{% url 'booktest:addhero' book.id %}">添加英雄</a>
    </div>
    <h2><a href="{% url 'booktest:index' %}">返回列表页</a></h2>
</body>
</html>

end/demo1/bookdemo/templates/edithero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑英雄</title>
</head>
<body>
    <form action="#" method="post">
        英雄名字：<input type="text" name="heroname" >
        <br>
        英雄技能: <input type="text" name="herocontent" >
        <br>
       {% if hero.gender == 'male' %}
         英雄性别：<input type="radio" name="sex" value="female" >女 <input type="radio" name="sex" value="male" checked>男
       {% else %}
         英雄性别：<input type="radio" name="sex" value="female" checked>女 <input type="radio" name="sex" value="male" >男
       {% endif %}
        <br>
        <input type="submit" value="提交">



    </form>

</body>
</html>

end/demo1/bookdemo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
         <h1>这里是首页 <a href="{% url 'polls:index' %}">这是投票页</a></h1>
        <div class="center">
           <div>
               <img src="/static/img/公众号.JPG" alt="">
           </div>
            
            <h2>这里显示所有书籍</h2>
            <ul>
                {% for book in books %}
                   <li>
                       {# <a href="/detail/{{book.id}}"> <li>{{book.id}}--{{book.title}}--{{book.price}}--{{book.pub_date}}</li> </a>#}
                       <a href="{% url 'booktest:detail' book.id %}"> {{book.id}}--{{book.title}}--{{book.price}}--{{book.pub_date}} </a>
                       <a href="{% url 'booktest:deletebook' book.id %}"> 删除 </a>
                   </li>
                {% endfor %}
            </ul>
            <h2>{#<a href="{% url 'booktest:addbook'>添加书籍</a></h2>#}

        </div>
    </div>

       

</body>
</html>