end/demo1/bookdemo/bookdemo/urls.py
from django.contrib import admin
from django.urls import path, include
#路由网址 每一个网址都需要绑定视图函数 视图函数给予页面返回
#每一个路由都需要和视图函数绑定
#MVT V 视图函数 3个作用 接受请求 处理数据 返回响应

urlpatterns = [


    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls', namespace='polls')),
    path('download', include('download.urls', namespace='download')),

    # 路由修改
    path('', include('booktest.urls', namespace='booktest'))

    #1.使用path将booktest的路由 进行包含
    # path('booktest/', include('booktest.urls'))


]
#项目的所有路由地址配置文件
#admin路由是django自带的后台管理路由
#总的路由列表==项目路由文件 使用include包含应用路由文件

#硬编码 在html文件中有很多超级链接 其中herf属性如果写成绝对路径 这种就叫硬编码
#在开发的过程中可能需要反复修改路由，若使用硬编码非常不方便
#需要解除硬编码
#1.需要给应用一个app_name='应用名' 写在应用的urls.py文件中
#2.在项目路由中给应用分流时 在include中提供命名空间
#3.在应用中给每一个路由一个名字
#4.在html中使用时，href={% url '应用名:路由名字'  实参列表 %}
#以前定位路由 靠总路由正则表达式+应用路由正则表达式
#接触硬编码后 使用 应用名字+应用路由名字

end/demo1/bookdemo/polls/urls.py
from django.conf.urls import url
from . import views
app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^detail/(\d+)/$', views.detail, name="detail"),
    url(r'^result/(\d+)/$', views.result, name='result'),
    url(r'^login/$', views.login, name='login'),
    url(r'^regist/$', views.regist, name='regist'),
    url(r'^logout/$', views.logout, name='logout'),
]

end/demo1/bookdemo/polls/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    """
    自定义用户类继承django自带的用户系统
    """
    telephone = models.CharField(max_length=20, verbose_name='手机号')
    questions = models.ManyToManyField('Question')




class Question(models.Model):
    title = models.CharField(max_length=50,verbose_name="投票问题")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    def __str__(self):
        return  self.title
    class Meta:
        ordering = ["-create_time"]
        verbose_name = "投票问题"
        verbose_name_plural = "投票问题"
class Choices(models.Model):
    content = models.CharField(max_length=50, verbose_name="选项")
    votes = models.PositiveIntegerField(verbose_name="得票数")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="choices")
    def __str__(self):
        return self.content
    class Meta:
        ordering = ["-create_time"]
        verbose_name = "选项"
        verbose_name_plural = "选项"

end/demo1/bookdemo/polls/forms.py
from django import forms
from .models import User

class RegistForm(forms.ModelForm):
    """
    定义一个注册表单类用于生成html表单
    """
    password2 = forms.CharField(widget=forms.PasswordInput,label="重复密码")
    class Meta:
        model = User
        fields = ["username","password"]
        labels = {
            'username': '用户名',
            'password': '密码'
        }
        help_texts = {
            'username': '大于3小于15',
            'password': '大于3小于15'
        }
        widgets = {
            'password': forms.PasswordInput

        }

end/demo1/bookdemo/polls/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse, FileResponse
from .models import *
from django.views.generic import View,TemplateView,ListView,CreateView,DeleteView,UpdateView,DateDetailView as DV
from django.contrib.auth import authenticate, login as lin, logout as lot
from .forms import RegistForm
def index(request):
    print("==========")
    # print(request)
    # print(dir(request))
    # print(request.headers)
    print(request.GET.get('hobbys'))
    print(request.GET.getlist('hobbys'))



    questions = Question.objects.all()
    return render(request, 'polls/index.html', {"questions": questions})

    # return HttpResponse('首页')

def detail(request,qid):
    print(qid, '===')
    if request.method == "GET":
        print('当前用户', request.user.username)
        if request.user and request.user.username != '':
            #已经登陆过了
            print('用户投过票的问题',request.user.questions,type(request.user.questions.all()))
            try:
                question = Question.objects.get(id=qid)
                if question in request.user.questions.all():
                    print('已经投过票')
                    url = reverse('polls:result', args=(qid))
                    return redirect(to=url)

                else:
                    try:
                        # question = Question.objects.get(id=qid)
                        return render(request, 'polls/detail.html', {"question": question})
                    except:
                        return HttpResponse('问题不合法')
                    # return HttpResponse('详情页'+qid)
            except Exception as e:
                print(e,'====')
                return HttpResponse('问题不合法')

        else:
            url = reverse('polls:login')+"?next=/polls/detail/"+qid+'/'
            return redirect(to=url)
    elif request.method == "POST":
        choiceid = request.POST.get('num')
        try:
            choice = Choices.objects.get(id=choiceid)
            choice.votes+=1
            choice.save()

            request.user.questions.add(Question.objects.get(id=qid))

            url = reverse("polls:result", args=(qid,))
            return redirect(to=url)
        except:
            return HttpResponse('选项不合法')



def result(request,qid):
    try:
        question = Question.objects.get(id=qid)
        return render(request,'polls/result.html', {"question":question})
    except:
        return HttpResponse('问题不合法')

# Create your views here.
# class ResultView(View):
#     def get(self,request,qid):
#         try:
#             question = Question.objects.get(id=qid)
#             return render(request,'polls:result.html', {'question:question'})
#         except Exception as e:
#             print(e)
#             return HttpResponse('问题不合法')
def login(request):
    if request.method == 'GET':
        return render(request,'polls/login.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        #可以使用django自带的用户认证系统 认证成功返回用户 失败返回None
        user = authenticate(username=username, password=password)
        if user:
            #调用django登陆方法，其实是为了生成cookie
            lin(request, user)
            next = request.GET.get("next")
            if next:
                url = next

            else:

                url = reverse('polls:index')
            return redirect(to=url)
        else:
            # url = reverse('polls:login')
            # return redirect(to=url)
            return render(request, 'polls/login.html', {'errors': '用户名密码不一致'})


def regist(request):
    if request.method == 'GET':
        # return render(request, 'polls/regist.html')
        rf = RegistForm()
        return render(request,'polls/regist.html', {'rf': rf})
    else:

        rf = RegistForm(request.POST)
        if rf.is_valid():
            print(rf,"++",rf.cleaned_data["username"])


            username = rf.cleaned_data["username"]
            password = rf.cleaned_data["password"]
            password2 = rf.cleaned_data["password2"]
            if User.objects.filter(username=username).count()>0:
                # return HttpResponse("用户名已存在")
                return render(request, 'polls/regist.html',{"errors":"用户名已存在"})
            else:
                if password == password2:
                    # User.objects.create_user(username=username, password=password)
                    rf.save()
                    url = reverse("polls:login")
                    return redirect(to=url)
                else:
                    return render(request, 'polls/regist.html', {"errors": "密码不一致"})
                    # return HttpResponse("密码不一致")
        else:
            return HttpResponse("未知错误")

def logout(request):
    lot(request)
    url = reverse('polls:index')
    return redirect(to=url)

end/demo1/bookdemo/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票结果页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
  <div class="container">
       {% block header %}
            <div>
               {% if request.user and request.user.username != ''%}
                  用户名：{{request.user.username}} <a href="{% url 'polls:logout' %}">退出</a>
               {% else %}
                  <a href="{% url 'polls:login' %}">登录</a> <a href="{% url 'polls:regist' %}">注册</a>
               {% endif%}

            </div>



        {% endblock %}

        {% block body %}
            这里是身体
        {% endblock %}

        {% block footer %}
            这里是底部
        {% endblock %}
    </div>

</body>
</html>

end/demo1/bookdemo/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block title %}
    投票页面
{% endblock %}


        {% block body %}
             <h2> 投票的问题是： {{question.title}} </h2>

        <ul>
            <h3>选项有</h3>

            <form action="#" method="post">
                {# {% csrf_token %} 这个标签可以请求获取csrftoken信息 #}
                {% csrf_token %}
                {% for c in question.choices.all %}
                    {% if forloop.counter == 1 %}
                        <li><input type="radio" checked name="num" value="{{c.id}}">     {{c.content}}</li>
                    {% else %}
                        <li><input type="radio"  name="num" value="{{c.id}}">     {{c.content}}</li>
                    {% endif %}

                {% endfor %}

                <input type="submit" value="投票">
            </form>
        </ul>

        <a href="{% url 'polls:index' %}">返回</a>
        {% endblock %}

end/demo1/bookdemo/templates/polls/index.html
{% extends 'polls/base.html' %}



{% block body %}
        <h2>投票问题列表</h2>
        <ul>
            {% for q in questions %}
                <li><a href="{% url 'polls:detail' q.id %}"> {{forloop.counter}} . {{q.title}}</a> </li>
            {% endfor %}
        </ul>
        {# {% include 'polls/other.html' %} #}
{% endblock %}

end/demo1/bookdemo/templates/polls/login.html
{% block body %}
<form action="#" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username" required>
    <br>
    密码: <input type="text" name="password" required>
    <br>
    <input type="submit" value="登录">
    {{errors}}


</form>


{% endblock%}

end/demo1/bookdemo/templates/polls/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

end/demo1/bookdemo/templates/polls/other.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

end/demo1/bookdemo/templates/polls/regist.html
{% block body %}
    {% comment %}
    <form action="#" method="post">
        {% csrf_token %}

        用户名：<input type="text" name="username" required>
        <br>
        密码: <input type="text" name="password" required>
        <br>
        重复密码: <input type="text" name="password2" required>
        <br>
        <input type="submit" value="注册">
        {{errors}}




    </form>
    {% endcomment %}

<form action="#" method="post">
    {% csrf_token %}
        {{rf.username.label}} : {{rf.username}}
        <br>
        {{rf.username.help_text}}
        <br>
        {{rf.password.label}} :{{rf.password}}
        <br>
        {{rf.password.help_text}}
        <br>
        {{rf.password2.label}} :{{rf.password}}
        <br>
        <input type="submit" value="注册">


</form>

{% endblock%}

end/demo1/bookdemo/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票结果页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        <h1>问题是：{{question.title}}</h1>

        <ul>
            <h2>得票情况：</h2>
            {% for c in question.choices.all %}
               <li>{{c.content}} {{c.votes}}票</li>
            {% endfor%}

        </ul>
        <a href="{% url 'polls:index' %}">返回首页</a>
    </div>
</body>
</html>